// <auto-generated />
namespace _3dsGallery.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserBio : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserBio));
        
        string IMigrationMetadata.Id
        {
            get { return "202605300747444_UserBio"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
