// <auto-generated />
namespace _3dsGallery.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;

    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddImageKitPictureStorage : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "202609201640000_AddImageKitPictureStorage"; }
        }

        string IMigrationMetadata.Source
        {
            get { return null; }
        }

        string IMigrationMetadata.Target
        {
            get { return null; }
        }
    }
}
